# Generated by Django 4.0.4 on 2022-09-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentTrack', '0007_alter_user_email_alter_user_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('teacher', 'teacher'), ('student', 'student'), ('admin', 'admin')], null=True),
        ),
    ]
