# Generated by Django 4.0.4 on 2022-07-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageusermodel',
            name='message',
            field=models.CharField(max_length=2000),
        ),
    ]
